"""empty message

Revision ID: 29e1a9242d3e
Revises: None
Create Date: 2015-04-29 13:35:34.483926

"""

# revision identifiers, used by Alembic.
revision = '29e1a9242d3e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baseblockmodel')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseblockmodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('block_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], [u'block.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
